const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base=process.env.UI_BASE_URL||'http://localhost:3192',out=path.resolve(process.env.UI_EVIDENCE_DIR||'.impeccable/review/deep-alignment/acceptance');
(async()=>{
 fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();const errors=[],passed=[],metrics=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{localStorage.setItem('orbit.locale','en');Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.copied=text;}}});});
 const ip='2001:4860:4860:0000:0000:0000:0000:8888';
 await page.route('**/api/rdap/**',route=>route.fulfill({json:{ip,registry:'ARIN',endpoint:'https://rdap.arin.net/registry/ip/'+ip,network:{startAddress:ip,endAddress:ip,cidrs:[],handle:'LONG-NETWORK-HANDLE-1234567890',name:'Long network name',type:'DIRECT ALLOCATION',ipVersion:'v6',country:'US',parentHandle:''},entities:[],events:[],remarks:[],notices:[],links:[],raw:{objectClassName:'ip network'}}}));
 await page.goto(base+'/geoip');await page.evaluate(()=>document.fonts.ready);
 for(const width of [320,390,600,768,769,1440]){
  await page.setViewportSize({width,height:844});const m=await page.evaluate(()=>{const r=s=>{const e=document.querySelector(s),b=e.getBoundingClientRect(),c=getComputedStyle(e);return{y:b.y,h:b.height,font:parseFloat(c.fontSize),line:c.lineHeight}};return{width:innerWidth,title:r('h1'),input:r('.lookup-form input'),overflow:document.documentElement.scrollWidth>innerWidth}});metrics.push(m);assert.equal(m.overflow,false);assert.equal(m.input.font,16);if(width===390){assert.equal(m.title.font,24);assert.ok(m.title.h<32);assert.equal(m.title.y,109);assert.ok(Math.abs(m.input.y-157.5)<1);}if(width===1440)assert.equal(m.input.h,52);
 }
 passed.push('GeoIP hero matches reference spacing and typography at six widths');
 await page.goto(base+'/whois/'+ip);await page.locator('.data-panel').waitFor({timeout:10000}).catch(async e=>{console.log(await page.locator('main').innerText(),await page.locator('#whois-ip').inputValue(),page.url());throw e;});await page.evaluate(()=>document.fonts.ready);
 for(const width of [320,390,768,769,1440]){
  await page.setViewportSize({width,height:844});const m=await page.evaluate(()=>{const title=document.querySelector('.panel-heading h2').getBoundingClientRect(),actions=document.querySelector('.panel-actions').getBoundingClientRect();return {overflow:document.documentElement.scrollWidth>innerWidth,overlap:title.right>actions.left&&title.bottom>actions.top,display:getComputedStyle(document.querySelector('.record-row')).display,color:getComputedStyle(document.querySelector('.record-value')).color}});assert.equal(m.overflow,false);assert.equal(m.overlap,false);assert.equal(m.display,width<=768?'block':'grid');assert.equal(m.color,'rgb(82, 82, 82)');
 }
 passed.push('Long IPv6 keeps header actions separate; tablet rows stack through 768px');
 const copy=page.locator('.record-row .copy-button').first();await copy.focus();assert.equal(await copy.evaluate(e=>getComputedStyle(e).opacity),'1');await copy.click();assert.equal(await page.evaluate(()=>window.copied),ip);await page.locator('.header-search input').focus();await page.mouse.move(0,0);assert.equal(await copy.getAttribute('data-state'),'copied');assert.equal(await copy.evaluate(e=>getComputedStyle(e).opacity),'1');
 passed.push('Keyboard copy preserves original IPv6 and keeps success feedback visible after focus leaves');
 await page.evaluate(()=>{navigator.clipboard.writeText=async()=>{throw new Error('Denied');}});const lastCopy=page.locator('.record-row .copy-button').last();await lastCopy.click();const failure=page.locator('.copy-error');await failure.waitFor();const clipping=await failure.evaluate(e=>{const a=e.getBoundingClientRect(),b=e.closest('.data-panel').getBoundingClientRect();return a.top<b.top||a.bottom>b.bottom||a.left<b.left||a.right>b.right});assert.equal(clipping,false);passed.push('Last-row copy failure stays inside the result panel');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'long-ipv6-mobile.png'),fullPage:true});await page.locator('.theme-switch').click();assert.equal(await page.locator('.record-value').first().evaluate(e=>getComputedStyle(e).color),'rgb(185, 185, 185)');await page.screenshot({path:path.join(out,'long-ipv6-dark.png'),fullPage:true});passed.push('Dark data text has explicit readable secondary color');
 assert.deepEqual(errors,[]);passed.push('No browser runtime errors');fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify({passed,metrics},null,2));await browser.close();console.log(JSON.stringify({passed},null,2));
})().catch(e=>{console.error(e);process.exit(1)});
