const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:900}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 let extra={};
 let loc={latitude:37.7749,longitude:-122.4194};
 await page.route('**/api/ip/**',r=>r.fulfill({json:{ip:'8.8.8.8',status:'partial',generation:'fixture',timestamp:new Date().toISOString(),sources:{maxmind:{label:'MaxMind',location:loc,network:{organization:'Google LLC'}},...extra},errors:{}}}));
 await page.goto(process.env.UI_BASE_URL || 'http://localhost:3190');
 const canvas=page.locator('.orbit-globe canvas');
 await page.waitForFunction(()=>!!document.querySelector('canvas')?.dataset.longitude);
 assert.equal(await page.getByRole('button',{name:/暂停动态|继续旋转|Pause motion|Resume motion/}).count(),0);
 const first=await canvas.getAttribute('data-longitude');await page.waitForTimeout(600);assert.notEqual(await canvas.getAttribute('data-longitude'),first);
 await page.locator('#ip-address').fill('8.8.8.8');await page.getByRole('button',{name:'查询',exact:true}).click();
 await page.waitForFunction(()=>Math.abs(+document.querySelector('canvas').dataset.longitude+122.4194)<.1);
 assert.match(await canvas.getAttribute('aria-label'),/37.7749/);
 await page.waitForFunction(()=>document.querySelector('canvas').dataset.motion==='settled');
 assert.equal(await canvas.getAttribute('data-longitude'),'-122.419');
 const settled=await canvas.getAttribute('data-longitude');
 await page.waitForTimeout(300);assert.equal(await canvas.getAttribute('data-longitude'),settled);

 fs.mkdirSync('.impeccable/review/orbit-motion',{recursive:true});
 await page.screenshot({path:'.impeccable/review/orbit-motion/desktop.png',fullPage:true});
 extra={zalt:{label:'Alternate',location:{latitude:51.5,longitude:0},network:{}}};
 await page.getByRole('button',{name:'查询',exact:true}).click();
 const alternate=page.locator('.result-table tbody tr').filter({hasText:'Alternate'});
 await alternate.locator('summary').click();await alternate.getByRole('button',{name:'定位到此来源'}).click();
 await page.waitForFunction(()=>Math.abs(+document.querySelector('canvas').dataset.latitude-51.5)<.1);
 extra={};loc={latitude:0,longitude:179};await page.getByRole('button',{name:'查询',exact:true}).click();
 await page.waitForFunction(()=>Math.abs(+document.querySelector('canvas').dataset.longitude-179)<.1);
 loc={latitude:0,longitude:-179};await page.getByRole('button',{name:'查询',exact:true}).click();await page.waitForTimeout(200);
 assert.ok(Math.abs(+(await canvas.getAttribute('data-longitude')))>175);
 await page.waitForFunction(()=>Math.abs(+document.querySelector('canvas').dataset.longitude+179)<.1);
 loc={};await page.getByRole('button',{name:'查询',exact:true}).click();await page.getByText('无可用坐标，保留视角').waitFor();
 const held=await canvas.getAttribute('data-longitude');await page.waitForTimeout(300);assert.equal(await canvas.getAttribute('data-longitude'),held);
 await page.emulateMedia({reducedMotion:'reduce'});loc={latitude:0,longitude:0};
 await page.getByRole('button',{name:'查询',exact:true}).click();await page.waitForFunction(()=>Math.abs(Number(document.querySelector('canvas').dataset.longitude))<0.1);
 await page.setViewportSize({width:390,height:812});await page.screenshot({path:'.impeccable/review/orbit-motion/mobile.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(errors,[]);
 fs.writeFileSync('.impeccable/review/orbit-motion/checks.json',JSON.stringify({passed:['idle rotates slowly','no manual motion control','query rotates to San Francisco','missing coordinates preserve view','zero coordinates valid','system reduced motion does not disable globe positioning','mobile no overflow','source selection rotates and scrolls','antimeridian uses short rotation','no runtime exceptions'],capturedAt:new Date().toISOString()},null,2));
 await page.goto(process.env.UI_BASE_URL || 'http://localhost:3190');
 await page.waitForFunction(()=>!!document.querySelector('canvas')?.dataset.longitude);
 const idleBefore=await page.locator('canvas').getAttribute('data-longitude');
 await page.waitForTimeout(700);
 assert.notEqual(await page.locator('canvas').getAttribute('data-longitude'),idleBefore);
 await browser.close();console.log('11 globe checks passed, including idle animation with reduced motion enabled');
})().catch(e=>{console.error(e);process.exit(1)});
